import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createApi, ApiError, queryString } from '../src/lib/api';
import { SessionController } from '../src/lib/session';
import type { Session } from '../src/types';
const baseUrl = process.env.MOBILE_TEST_API_URL;
if (!baseUrl || !/^http:\/\/(127\.0\.0\.1|localhost):\d+\/api$/.test(baseUrl)) throw new Error('Use an isolated local backend for integration tests.');
test('mobile client and web contract share real CRUD, counts, relationships, filtering and session revocation', async () => {
  let current: Session | null = null;
  const api = createApi({ baseUrl, session: () => current, unauthorized: () => { current = null; } });
  const email = 'android-contract-' + Date.now() + '@example.test'; const password = 'Test-password-42';
  await api.register('Android Contract', email, password); current = await api.login(email, password);
  const headers = { Authorization: 'Bearer ' + current.accessToken, 'Content-Type': 'application/json' };
  const webProject = await fetch(baseUrl + '/projects', { method: 'POST', headers, body: JSON.stringify({ name: 'Web project', status: 'IN_PROGRESS' }) });
  assert.equal(webProject.status, 201); const project = (await webProject.json()).data;
  assert.equal((await api.projects({ search: 'Web project' }))[0].id, project.id);
  const task = await api.saveTask({ name: 'Android task', description: null, projectId: project.id, priority: 'HIGH', status: 'PENDING', dueDate: null });
  const fromWeb = await fetch(baseUrl + '/tasks?projectId=' + project.id, { headers });
  assert.equal((await fromWeb.json()).data[0].id, task.id);
  await api.saveTask({ name: 'Changed %&_🔷 on Android', status: 'COMPLETED' }, task.id);
  const updatedWeb = await fetch(baseUrl + '/tasks/' + task.id, { headers });
  assert.equal((await updatedWeb.json()).data.status, 'COMPLETED');
  assert.equal((await api.tasks({ projectId: project.id, search: '%&_🔷', status: 'COMPLETED', priority: 'HIGH' })).length, 1);
  assert.deepEqual(await api.dashboard(), { totalProjects: 1, totalTasks: 1, completedTasks: 1, pendingTasks: 0, projectsInProgress: 1 });
  await api.saveProject({ name: 'Web project updated', description: null, status: 'COMPLETED', startDate: '2026-10-01', endDate: '2026-10-31' }, project.id);
  await api.deleteTask(task.id); assert.equal((await api.tasks()).length, 0);
  await api.saveTask({ name: 'Cascade task', description: null, projectId: project.id, priority: 'LOW', status: 'IN_PROGRESS', dueDate: null });
  await api.deleteProject(project.id); assert.equal((await api.tasks()).length, 0);
  const token = current!.accessToken; await api.logout();
  const revoked = await fetch(baseUrl + '/auth/me', { headers: { Authorization: 'Bearer ' + token } }); assert.equal(revoked.status, 401);
  current = await api.login(email, password); current.accessToken += 'invalid';
  await assert.rejects(api.me(), error => error instanceof ApiError && error.status === 401); assert.equal(current, null);
});
test('backend rejection expires secure persisted authentication through the same client', async () => {
  let saved: string | null = null; let controller: SessionController;
  const api = createApi({ baseUrl, session: () => controller?.current() || null, unauthorized: token => { void controller.expire(token); } });
  controller = new SessionController(api, { get: async () => saved, set: async value => { saved = value; }, remove: async () => { saved = null; } });
  const email = 'android-expiry-' + Date.now() + '@example.test'; await api.register('Expiry Test', email, 'Test-password-42');
  await controller.login(email, 'Test-password-42'); await api.logout();
  await assert.rejects(api.me(), error => error instanceof ApiError && error.status === 401);
  await new Promise(done => setTimeout(done, 0)); assert.equal(saved, null); assert.equal(controller.snapshot().status, 'signedOut');
  assert.equal(queryString({ search: 'a %&_🔷', status: '' }), '?search=a%20%25%26_%F0%9F%94%B7');
});
