import { useState, type ReactNode } from 'react';
import { ActivityIndicator, Keyboard, KeyboardAvoidingView, Modal, Platform, Pressable, RefreshControl, ScrollView, Text, TextInput, View, type StyleProp, type ViewStyle, type TextInputProps } from 'react-native';
import { DateTimePickerAndroid } from '@react-native-community/datetimepicker';
import { useNetInfo } from '@react-native-community/netinfo';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Svg, { Circle, Path } from 'react-native-svg';
import Ionicons from '@expo/vector-icons/Ionicons';
import { useTheme } from './ThemeProvider';
import { calendarDate, formatDate } from '../lib/validation';
import { labels } from '../types';
export function Type({ children, variant = 'body', muted = false, style, testID, numberOfLines }: { children: ReactNode; numberOfLines?: number; variant?: 'title' | 'heading' | 'body' | 'small' | 'label'; muted?: boolean; style?: StyleProp<import('react-native').TextStyle>; testID?: string }) {
  const { colors } = useTheme();
  return <Text testID={testID} numberOfLines={numberOfLines} accessibilityRole={variant === 'title' || variant === 'heading' ? 'header' : undefined} style={[{ color: muted ? colors.muted : colors.text, fontFamily: ['title', 'heading', 'label'].includes(variant) ? 'SpaceGrotesk' : 'Inter', fontSize: variant === 'title' ? 34 : variant === 'heading' ? 22 : variant === 'small' ? 12 : variant === 'label' ? 13 : 14, lineHeight: variant === 'title' ? 40 : variant === 'heading' ? 28 : 21 }, style]}>{children}</Text>;
}
export function Geometry() { const { colors } = useTheme(); return <View accessible={false} style={{ flexDirection: 'row', alignItems: 'center', gap: 7 }}><View style={{ width: 16, height: 16, backgroundColor: colors.red, borderRadius: 8, borderWidth: 1, borderColor: '#1a1a1a' }} /><Svg width={18} height={18}><Path d="M9 1 L18 17 L0 17 Z" fill={colors.yellow} /></Svg><View style={{ width: 15, height: 15, backgroundColor: colors.blue, borderWidth: 1, borderColor: '#1a1a1a' }} /></View>; }
export function ThemeToggle() { const { colors, isDark, toggle } = useTheme(); return <Pressable testID="theme-toggle" accessibilityRole="button" accessibilityLabel={isDark ? 'Switch to light mode' : 'Switch to dark mode'} onPress={toggle} style={{ width: 48, height: 48, alignItems: 'center', justifyContent: 'center' }}><Ionicons name={isDark ? 'sunny-outline' : 'moon-outline'} size={22} color={colors.text} /></Pressable>; }
export function Button({ label, onPress, variant = 'plain', busy = false, disabled = false, testID, style }: { label: string; onPress: () => void; variant?: 'primary' | 'danger' | 'plain'; busy?: boolean; disabled?: boolean; testID?: string; style?: StyleProp<ViewStyle> }) {
  const { colors } = useTheme();
  const ink = variant === 'primary' || variant === 'danger' ? '#1a1a1a' : colors.text;
  return <Pressable testID={testID} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled: disabled || busy, busy }} disabled={disabled || busy} onPress={onPress} style={({ pressed }) => [{ minHeight: 48, paddingVertical: 12, paddingHorizontal: 16, borderWidth: 2, borderColor: variant === 'plain' ? colors.border : '#1a1a1a', backgroundColor: variant === 'primary' ? colors.yellow : variant === 'danger' ? colors.red : colors.panel, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, opacity: disabled || busy ? .55 : pressed ? .8 : 1 }, style]}>{busy && <ActivityIndicator color={ink} size="small" />}<Text style={{ color: ink, fontFamily: 'SpaceGrotesk', fontSize: 14, flexShrink: 1 }}>{label}</Text></Pressable>;
}
export function Card({ children, style }: { children: ReactNode; style?: StyleProp<ViewStyle> }) { const { colors } = useTheme(); return <View style={[{ backgroundColor: colors.panel, borderWidth: 2, borderColor: colors.border, borderRadius: 14, padding: 20, gap: 14 }, style]}>{children}</View>; }
export function Screen({ children, refreshing = false, onRefresh }: { children: ReactNode; refreshing?: boolean; onRefresh?: () => void }) {
  const { colors } = useTheme(); const net = useNetInfo(); const insets = useSafeAreaInsets();
  return <KeyboardAvoidingView style={{ flex: 1, backgroundColor: colors.bg }} behavior={Platform.OS === 'ios' ? 'padding' : undefined} keyboardVerticalOffset={90}>
    <ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={{ padding: 20, gap: 20, paddingBottom: Math.max(insets.bottom, 20) + 28 }} refreshControl={onRefresh ? <RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.text} colors={[colors.blue]} /> : undefined}>
      {net.isConnected === false && <Card style={{ backgroundColor: colors.raised }}><Type variant="small">You’re offline. Connect to refresh or save changes.</Type></Card>}
      {children}
    </ScrollView>
  </KeyboardAvoidingView>;
}
export function Heading({ title, description }: { title: string; description: string }) { const { colors } = useTheme(); return <View style={{ gap: 8, paddingBottom: 24, borderBottomWidth: 2, borderColor: colors.border }}><Type variant="small" muted>Your workspace</Type><Type variant="title">{title}<Text style={{ color: colors.link }}> /</Text></Type><Type muted>{description}</Type></View>; }
export function Loading({ label = 'Loading your workspace…' }: { label?: string }) { const { colors } = useTheme(); return <View accessibilityRole="progressbar" accessibilityLabel={label} style={{ gap: 14 }}><Type muted variant="small">{label}</Type>{[0, 1, 2].map(key => <Card key={key}><View style={{ height: 13, backgroundColor: colors.raised, width: '65%' }} /><View style={{ height: 30, backgroundColor: colors.raised, width: '40%' }} /><View style={{ height: 13, backgroundColor: colors.raised, width: '80%' }} /></Card>)}</View>; }
export function ErrorState({ text, retry }: { text: string; retry?: () => void }) { return <Card><Type variant="heading">Something went wrong</Type><ErrorText text={text} />{retry && <Button label="Try again" onPress={retry} />}</Card>; }
export function ErrorText({ text }: { text: string }) { const { colors } = useTheme(); return text ? <View style={{ padding: 14, borderWidth: 1, borderColor: colors.error, backgroundColor: colors.redSoft, borderRadius: 6 }}><Text accessibilityRole="alert" accessibilityLiveRegion="assertive" style={{ color: colors.error, fontFamily: 'Inter', fontSize: 13, lineHeight: 20 }}>{text}</Text></View> : null; }
export function EmptyState({ title, description, action, label }: { title: string; description: string; action?: () => void; label?: string }) { return <Card style={{ alignItems: 'flex-start', borderStyle: 'dashed', paddingVertical: 30 }}><Geometry /><Type variant="heading">{title}</Type><Type muted>{description}</Type>{action && <Button label={label || 'Get started'} onPress={action} variant="primary" />}</Card>; }
export function Field({ label, value, onChangeText, hint, ...props }: TextInputProps & { label: string; value: string; onChangeText: (value: string) => void; hint?: string }) { const { colors } = useTheme(); return <View style={{ gap: 8 }}><Type variant="label">{label}</Type><TextInput {...props} accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholderTextColor={colors.muted} selectionColor={colors.blue} style={[{ color: colors.text, backgroundColor: colors.panel, borderWidth: 2, borderColor: colors.border, borderRadius: 6, minHeight: 50, padding: 12, fontSize: 14, fontFamily: 'Inter', textAlignVertical: props.multiline ? 'top' : 'center' }, props.style]} />{hint && <Type variant="small" muted>{hint}</Type>}</View>; }
export interface Option { value: string; label: string }
export function Choice({ label, value, options, onChange, testID, disabled = false }: { label: string; value: string; options: Option[]; onChange: (value: string) => void; testID?: string; disabled?: boolean }) {
  const [open, setOpen] = useState(false); const { colors } = useTheme(); const insets = useSafeAreaInsets();
  return <View style={{ gap: 8 }}><Type variant="label">{label}</Type><Pressable disabled={disabled} testID={testID} accessibilityRole="button" accessibilityLabel={label + ': ' + (options.find(option => option.value === value)?.label || 'Choose an option')} onPress={() => { Keyboard.dismiss(); setOpen(true); }} style={{ minHeight: 50, padding: 12, borderWidth: 2, borderColor: colors.border, backgroundColor: colors.panel, borderRadius: 6, flexDirection: 'row', alignItems: 'center', gap: 10, opacity: disabled ? .5 : 1 }}><Type style={{ flex: 1 }}>{options.find(option => option.value === value)?.label || 'Choose an option'}</Type><Ionicons name="chevron-down" size={18} color={colors.text} /></Pressable>
    <Modal visible={open} transparent animationType="slide" onRequestClose={() => setOpen(false)}><View style={{ flex: 1, justifyContent: 'flex-end', backgroundColor: '#00000099' }}><Pressable accessibilityLabel="Close choices" accessibilityRole="button" onPress={() => setOpen(false)} style={{ flex: 1 }} /><View accessibilityViewIsModal style={{ maxHeight: '80%', padding: 22, paddingBottom: insets.bottom + 22, gap: 16, backgroundColor: colors.bg, borderTopWidth: 2, borderColor: colors.border }}><Type variant="heading">{label}</Type><ScrollView keyboardShouldPersistTaps="handled">{options.map(option => <Pressable key={option.value} testID={(testID || 'choice') + '-' + (option.value || 'all')} accessibilityRole="radio" accessibilityState={{ checked: option.value === value }} onPress={() => { onChange(option.value); setOpen(false); }} style={{ paddingVertical: 16, borderBottomWidth: 1, borderColor: colors.subtle, flexDirection: 'row', alignItems: 'center', gap: 14 }}><Type style={{ flex: 1 }}>{option.label}</Type>{option.value === value && <Ionicons name="checkmark-circle" size={22} color={colors.link} />}</Pressable>)}</ScrollView><Button label="Cancel" onPress={() => setOpen(false)} /></View></View></Modal>
  </View>;
}
export function DateField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  return <View style={{ gap: 8 }}><Type variant="label">{label}</Type><View style={{ flexDirection: 'row', gap: 10 }}><Button label={value ? formatDate(value) : 'Choose a date'} style={{ flex: 1 }} onPress={() => { Keyboard.dismiss(); DateTimePickerAndroid.open({ value: value ? new Date(value + 'T12:00:00') : new Date(), mode: 'date', onChange: (event, selected) => { if (event.type === 'set' && selected) onChange(calendarDate(selected)); } }); }} />{!!value && <Button label="Clear" onPress={() => onChange('')} />}</View></View>;
}
export function Badge({ value }: { value: keyof typeof labels }) { const { colors } = useTheme(); const progress = value === 'IN_PROGRESS' || value === 'MEDIUM'; const complete = value === 'COMPLETED'; const high = value === 'HIGH'; return <View style={{ alignSelf: 'flex-start', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 99, borderWidth: 1, borderColor: colors.border, backgroundColor: progress ? colors.yellow : complete ? colors.blue : high ? colors.redSoft : value === 'LOW' ? colors.blueSoft : colors.raised }}><Text style={{ color: progress ? '#1a1a1a' : complete ? '#ffffff' : high ? colors.error : colors.text, fontFamily: 'SpaceGrotesk', fontSize: 12 }}>{labels[value]}</Text></View>; }
export function ProgressRing({ completed, total }: { completed: number; total: number }) { const { colors } = useTheme(); const percent = total ? Math.round(completed / total * 100) : 0; return <View accessibilityLabel={completed + ' of ' + total + ' tasks completed'} style={{ width: 92, height: 92, alignItems: 'center', justifyContent: 'center' }}><Svg width={92} height={92} style={{ position: 'absolute' }}><Circle cx={46} cy={46} r={37} fill="none" stroke={colors.raised} strokeWidth={8} /><Circle cx={46} cy={46} r={37} fill="none" stroke={colors.blue} strokeWidth={8} strokeDasharray="232.48" strokeDashoffset={232.48 * (1 - percent / 100)} rotation={-90} origin="46,46" strokeLinecap="round" /></Svg><Type variant="heading">{percent}%</Type></View>; }
