import { test, expect, type Page, type APIRequestContext } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const password = 'Test-password-42';
function email() { return 'web-' + Date.now() + '-' + Math.random().toString(16).slice(2) + '@example.test'; }
async function signIn(page: Page, value: string) {
  await page.goto('/login');
  await page.getByLabel('Email', { exact: true }).fill(value);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: false })).toBeVisible();
}
async function register(request: APIRequestContext) {
  const value = email();
  const response = await request.post('http://127.0.0.1:3001/api/auth/register', { data: { fullName: 'Web Test', email: value, password } });
  expect(response.status()).toBe(201);
  return value;
}
async function screenshot(page: Page, name: string) {
  await page.screenshot({ path: 'test-results/screenshots/' + name + '.png', fullPage: true });
}
test('complete real-backend workflow, editing, filtering, deletion, themes and accessibility', async ({ page }) => {
  const value = email();
  const runtimeErrors: string[] = [];
  page.on('pageerror', error => runtimeErrors.push(error.message));
  await page.goto('/register');
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.getByLabel('Full name', { exact: true }).fill('Alex Morgan');
  await page.getByLabel('Email', { exact: true }).fill(value);
  await page.getByLabel('Password', { exact: false }).first().fill(password);
  await page.getByLabel('Confirm password', { exact: true }).fill('Does-not-match');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('passwords don’t match');
  await page.getByLabel('Confirm password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByText('Your account is ready.')).toBeVisible();
  await page.getByLabel('Password', { exact: true }).fill('Incorrect-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('email or password doesn’t match');
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByTestId('metric-totalProjects').getByText('0', { exact: true })).toBeVisible();
  await expect(page.getByText('Alex Morgan', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Switch to dark mode' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await expect(page.getByTestId('metric-totalProjects')).toBeVisible();
  await screenshot(page, 'dashboard-empty-dark');
  await page.getByRole('button', { name: 'Create a project', exact: true }).first().click();
  let dialog = page.getByRole('dialog');
  await dialog.getByLabel('Project name').fill('Website launch');
  await dialog.getByLabel('Description (optional)').fill('Prepare our new website.');
  await dialog.getByLabel('Status', { exact: true }).selectOption('IN_PROGRESS');
  await dialog.getByLabel('Start date (optional)').fill('2026-10-20');
  await dialog.getByLabel('End date (optional)').fill('2026-10-10');
  await dialog.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('end date must be on or after');
  await dialog.getByLabel('End date (optional)').fill('2026-10-30');
  await dialog.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByTestId('metric-totalProjects').getByText('1', { exact: true })).toBeVisible();
  await expect(page.getByTestId('metric-projectsInProgress').getByText('1', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Website launch', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Website launch', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'No tasks yet' })).toBeVisible();
  await page.getByRole('button', { name: 'Edit project', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Description (optional)').fill('A thoughtful launch for our new website.');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.locator('.project-description')).toContainText('A thoughtful launch');
  await page.getByRole('button', { name: 'Create a task', exact: true }).first().click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Task name').fill('Review homepage');
  await dialog.getByLabel('Description (optional)').fill('Check content and layout.');
  await expect(dialog.getByLabel('Project', { exact: true }).locator('option:checked')).toHaveText('Website launch');
  await dialog.getByLabel('Priority', { exact: true }).selectOption('HIGH');
  await dialog.getByLabel('Due date (optional)').fill('2026-10-25');
  await dialog.getByRole('button', { name: 'Create task', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.locator('.task-main>strong')).toHaveText('Review homepage');
  await page.getByRole('button', { name: 'Edit Review homepage', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Task name').fill('Review launch content');
  await dialog.getByLabel('Status', { exact: true }).selectOption('IN_PROGRESS');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByLabel('Status for Review launch content').selectOption('PENDING');
  await expect(page.getByLabel('Status for Review launch content')).toBeEnabled();
  await page.getByRole('button', { name: 'Mark Review launch content completed' }).click();
  await expect(page.getByLabel('Status for Review launch content')).toHaveValue('COMPLETED');
  await expect(page.getByText('1 of 1 tasks completed', { exact: true })).toBeVisible();
  await screenshot(page, 'project-detail-dark');
  await page.locator('.sidebar').getByRole('link', { name: 'Dashboard', exact: true }).click();
  await expect(page.getByTestId('metric-totalTasks').getByText('1', { exact: true })).toBeVisible();
  await expect(page.getByTestId('metric-completedTasks').getByText('1', { exact: true })).toBeVisible();
  await expect(page.getByTestId('metric-pendingTasks').getByText('0', { exact: true })).toBeVisible();
  await screenshot(page, 'dashboard-dark');
  await page.getByRole('button', { name: 'Switch to light mode' }).click();
  await screenshot(page, 'dashboard-light');
  await page.locator('.sidebar').getByRole('link', { name: 'Tasks', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Search tasks' }).fill('Review launch');
  await page.locator('.filter-bar').getByLabel('Status', { exact: true }).selectOption('COMPLETED');
  await page.locator('.filter-bar').getByLabel('Priority', { exact: true }).selectOption('HIGH');
  await page.locator('.filter-bar').getByLabel('Project', { exact: true }).selectOption({ label: 'Website launch' });
  await expect(page.locator('.task-main>strong')).toHaveText('Review launch content');
  await page.getByRole('searchbox', { name: 'Search tasks' }).fill('No such task');
  await expect(page.getByRole('heading', { name: 'No tasks found' })).toBeVisible();
  await page.getByRole('button', { name: 'Clear filters', exact: true }).first().click();
  await expect(page.locator('.task-main>strong')).toHaveText('Review launch content');
  await screenshot(page, 'tasks-light');
  const lightAxe = await new AxeBuilder({ page }).analyze();
  expect(lightAxe.violations).toEqual([]);
  await page.getByRole('button', { name: 'Switch to dark mode' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  const darkAxe = await new AxeBuilder({ page }).analyze();
  expect(darkAxe.violations).toEqual([]);
  for (const width of [1024, 768, 390]) {
    await page.setViewportSize({ width, height: 900 });
    if (width === 390) await expect(page.locator('.sidebar')).not.toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await screenshot(page, 'tasks-dark-' + width);
  }
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.locator('.sidebar').getByRole('link', { name: 'Projects', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Projects', exact: false }).first()).toBeVisible();
  await page.getByRole('searchbox', { name: 'Search projects' }).fill('Website');
  await page.getByRole('button', { name: /^In progress/ }).click();
  await expect(page.getByRole('link', { name: 'Website launch', exact: true })).toBeVisible();
  await screenshot(page, 'projects-mobile-dark');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await screenshot(page, 'projects-dark');
  await page.getByRole('button', { name: 'Switch to light mode' }).click();
  await screenshot(page, 'projects-light');
  await page.getByRole('link', { name: 'Website launch', exact: true }).click();
  await screenshot(page, 'project-detail-light');
  await page.getByRole('button', { name: 'Delete Review launch content', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByRole('button', { name: 'Keep task' }).click();
  await expect(page.locator('.task-main>strong')).toHaveText('Review launch content');
  await page.getByRole('button', { name: 'Delete Review launch content', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Delete task', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'No tasks yet' })).toBeVisible();
  await page.getByRole('button', { name: 'Delete project', exact: true }).click();
  dialog = page.getByRole('dialog');
  await expect(dialog).toContainText('All tasks in this project will also be deleted.');
  await dialog.getByRole('button', { name: 'Delete project', exact: true }).click();
  await expect(page).toHaveURL(/\/projects$/);
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  await page.goBack();
  await expect(page).toHaveURL(/\/login$/);
  await expect(page.getByRole('heading', { name: 'Welcome back', exact: true })).toBeVisible();
  await page.reload();
  await expect(page).toHaveURL(/\/login$/);
  await page.goto('/tasks');
  await expect(page).toHaveURL(/\/login$/);
  expect(runtimeErrors).toEqual([]);
});
test('network recovery and real-backend rejection of an invalid persisted token', async ({ page, request }) => {
  const value = await register(request);
  await signIn(page, value);
  await page.route('**/api/projects*', route => route.abort());
  await page.locator('.sidebar').getByRole('link', { name: 'Projects', exact: true }).click();
  // Force a fresh fetch rather than relying on the cached dashboard list.
  await page.reload();
  await expect(page.getByRole('alert').first()).toContainText('couldn’t connect');
  await page.unroute('**/api/projects*');
  await page.getByRole('button', { name: 'Try again', exact: true }).first().click();
  await expect(page.getByRole('heading', { name: 'No projects yet' })).toBeVisible();
  await page.evaluate(() => {
    const value = JSON.parse(localStorage.getItem('ismo.session')!);
    value.accessToken += 'invalid';
    localStorage.setItem('ismo.session', JSON.stringify(value));
  });
  await page.reload();
  await expect(page).toHaveURL(/\/login$/);
  await expect(page.getByText('Your session has expired. Please sign in to continue.')).toBeVisible();
  expect(await page.evaluate(() => localStorage.getItem('ismo.session'))).toBeNull();
});
test('keyboard dialogs, project movement, cascade deletion and scheduled session expiry', async ({ page, request }) => {
  const value = await register(request);
  await signIn(page, value);
  const session = await page.evaluate(() => JSON.parse(localStorage.getItem('ismo.session')!));
  const headers = { Authorization: 'Bearer ' + session.accessToken };
  const create = async (name: string) => {
    const result = await request.post('http://127.0.0.1:3001/api/projects', { headers, data: { name } });
    expect(result.status()).toBe(201);
    return (await result.json()).data;
  };
  const first = await create('First project');
  const second = await create('Second project');
  const created = await request.post('http://127.0.0.1:3001/api/tasks', { headers, data: { name: 'Move this task', projectId: first.id } });
  expect(created.status()).toBe(201);
  await page.goto('/projects/' + first.id);
  await page.getByRole('button', { name: 'Create a task', exact: true }).first().click();
  await expect(page.getByRole('dialog').getByLabel('Task name')).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Create a task', exact: true }).first()).toBeFocused();
  await page.getByRole('button', { name: 'Edit Move this task', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Project', { exact: true }).selectOption(second.id);
  await page.getByRole('dialog').getByRole('button', { name: 'Save changes' }).click();
  await expect(page.getByRole('heading', { name: 'No tasks yet' })).toBeVisible();
  await page.goto('/projects/' + second.id);
  await expect(page.locator('.task-main>strong')).toHaveText('Move this task');
  await page.getByRole('button', { name: 'Delete project', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Delete project', exact: true }).click();
  const remaining = await request.get('http://127.0.0.1:3001/api/tasks', { headers });
  expect((await remaining.json()).data).toEqual([]);
  await page.evaluate(() => {
    const value = JSON.parse(localStorage.getItem('ismo.session')!);
    value.expiresAt = new Date(Date.now() + 5000).toISOString();
    localStorage.setItem('ismo.session', JSON.stringify(value));
  });
  await page.reload();
  await expect(page).toHaveURL(/\/login$/);
  await expect(page.getByText('Your session has expired. Please sign in to continue.')).toBeVisible();
});

test('sessions synchronize across tabs and expired saved sessions explain the redirect', async ({ page, context, request }) => {
  const value = await register(request);
  await signIn(page, value);
  const second = await context.newPage();
  await second.goto('/tasks');
  await expect(second.getByRole('heading', { name: 'Tasks', exact: false }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
  await expect(second).toHaveURL(/\/login$/);
  await signIn(second, value);
  await expect(page.getByTestId('metric-totalProjects')).toBeVisible();
  await page.close();
  await second.evaluate(() => {
    const saved = JSON.parse(localStorage.getItem('ismo.session')!);
    saved.expiresAt = new Date(Date.now() - 1000).toISOString();
    localStorage.setItem('ismo.session', JSON.stringify(saved));
  });
  await second.goto('/tasks');
  await expect(second).toHaveURL(/\/login$/);
  await expect(second.getByText('Your session has expired. Please sign in to continue.')).toBeVisible();
});
